project:
  type: website

website:
  title: "iBehave Open Technology Support"
  search: true
  reader-mode: true
  navbar:
    left:
      - href: course-index.qmd
        text: Courses
      - href: tutorial-index.qmd
        text: Tutorials
      - href: about.qmd
        text: About 

format:
  html:
    theme: journal

# Set the language that should be used for Quarto websites
# https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language
lang: en

# Set default options for every webpage that may or may not include Pyodide.
pyodide: 
  show-startup-message: false    # Display status of Pyodide initialization

# Attach Pyodide to every page
filters:
  - pyodide